<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
    <line>
      <![CDATA[=====Screenshot of ValidLogin taken successfully======
]]>
    </line>
    <line>
      <![CDATA[=====Screenshot of ApplyLeave taken successfully======
]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="149413" started-at="2017-05-16T08:06:54Z" finished-at="2017-05-16T08:09:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="149413" started-at="2017-05-16T08:06:54Z" finished-at="2017-05-16T08:09:24Z">
      <class name="com.RequestFunctionality.LeaveRequest">
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.RequestFunctionality.LeaveRequest@68be2bc2]" name="SetUp" is-config="true" duration-ms="7558" started-at="2017-05-16T13:36:54Z" finished-at="2017-05-16T13:37:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="CancelLeave()[pri:0, instance:com.RequestFunctionality.LeaveRequest@68be2bc2]" name="CancelLeave" duration-ms="9" started-at="2017-05-16T13:37:02Z" finished-at="2017-05-16T13:37:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CancelLeave -->
        <test-method status="PASS" signature="TestFaliure(org.testng.ITestResult)[pri:0, instance:com.RequestFunctionality.LeaveRequest@68be2bc2]" name="TestFaliure" is-config="true" duration-ms="2" started-at="2017-05-16T13:37:02Z" finished-at="2017-05-16T13:37:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CancelLeave status=SUCCESS method=LeaveRequest.CancelLeave()[pri:0, instance:com.RequestFunctionality.LeaveRequest@68be2bc2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestFaliure -->
        <test-method status="FAIL" signature="ApplyLeave()[pri:5, instance:com.RequestFunctionality.LeaveRequest@68be2bc2]" name="ApplyLeave" duration-ms="10981" started-at="2017-05-16T13:37:02Z" description="TC perform Sending leave request to respective Manager" finished-at="2017-05-16T13:37:13Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at org.openqa.selenium.support.ui.FluentWait.<init>(FluentWait.java:102)
	at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:71)
	at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:45)
	at com.Libaray.ExplicityWait.waitCall(ExplicityWait.java:15)
	at com.RequestFunctionality.LeaveRequest.ApplyLeave(LeaveRequest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[=====Screenshot of ValidLogin taken successfully======
]]>
            </line>
          </reporter-output>
        </test-method> <!-- ApplyLeave -->
        <test-method status="PASS" signature="TestFaliure(org.testng.ITestResult)[pri:0, instance:com.RequestFunctionality.LeaveRequest@68be2bc2]" name="TestFaliure" is-config="true" duration-ms="312" started-at="2017-05-16T13:37:13Z" finished-at="2017-05-16T13:37:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ApplyLeave status=FAILURE method=LeaveRequest.ApplyLeave()[pri:5, instance:com.RequestFunctionality.LeaveRequest@68be2bc2] output======Screenshot of ValidLogin taken successfully======
]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[=====Screenshot of ApplyLeave taken successfully======
]]>
            </line>
          </reporter-output>
        </test-method> <!-- TestFaliure -->
        <test-method status="FAIL" signature="ManagerApproval()[pri:6, instance:com.RequestFunctionality.LeaveRequest@68be2bc2]" name="ManagerApproval" duration-ms="128997" started-at="2017-05-16T13:37:13Z" description="TC perform Sending leave request to respective Manger" finished-at="2017-05-16T13:39:22Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.RequestFunctionality.LeaveRequest.ManagerApproval(LeaveRequest.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ManagerApproval -->
        <test-method status="PASS" signature="TestFaliure(org.testng.ITestResult)[pri:0, instance:com.RequestFunctionality.LeaveRequest@68be2bc2]" name="TestFaliure" is-config="true" duration-ms="23" started-at="2017-05-16T13:39:22Z" finished-at="2017-05-16T13:39:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ManagerApproval status=FAILURE method=LeaveRequest.ManagerApproval()[pri:6, instance:com.RequestFunctionality.LeaveRequest@68be2bc2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestFaliure -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.RequestFunctionality.LeaveRequest@68be2bc2]" name="teardown" is-config="true" duration-ms="1494" started-at="2017-05-16T13:39:22Z" finished-at="2017-05-16T13:39:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.RequestFunctionality.LeaveRequest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
